const D={departments:[
["🎵","Music & Choir Department","Worship • Praise • Music Ministry","To lead the congregation in Christ-centered worship, praise and spiritual songs.","Choir, Worship Team, Instrumentalists, Music Training and Choir Administration.",["Leading worship and praise.","Coordinating rehearsals.","Training singers and instrumentalists.","Maintaining spiritual and disciplinary standards.","Coordinating music for services and special programmes."]],
["📖","Evangelism Department","Gospel Outreach • Missions • Discipleship","To proclaim the Gospel and reach people with the message of Jesus Christ.","Outreach Team, Street Evangelism, House-to-House Evangelism, Missions, Follow-Up Team and Discipleship.",["Organizing evangelistic outreaches.","Following up new converts.","Supporting missionary activities.","Distributing Gospel materials.","Encouraging members to participate in evangelism."]],
["🙏","Prayer Department","Intercession • Prayer • Fasting","To establish and coordinate the prayer life of the Mission.","Intercessory Prayer, Prayer Meetings, Prayer Chains, Fasting & Prayer and Special Prayer Teams.",["Organizing corporate prayer.","Coordinating prayer meetings.","Interceding for the church and its leadership.","Praying for members, community and nations.","Maintaining prayer schedules."]],
["👧","Children's Department","Children • Bible Teaching • Discipleship","To teach children the Word of God and provide age-appropriate Christian discipleship.","Nursery, Primary Children, Junior Children, Children's Choir and Bible Teaching.",["Biblical teaching.","Children's activities.","Children's worship and Bible activities.","Safeguarding and supervision.","Encouraging parents in Christian upbringing."]],
["👩","Women's Department","Fellowship • Discipleship • Service","To provide fellowship, discipleship, prayer, service, mentoring and appropriate ministry opportunities for women.","",["Bible study.","Prayer meetings.","Women's conferences.","Mentoring.","Welfare support.","Evangelism.","Family-focused programmes.","Skills and development activities."]],
["👨","Men's Department","Leadership • Responsibility • Fellowship","To encourage men to grow in Christ, character, responsibility, leadership, family service and evangelistic commitment.","",["Men's Bible studies.","Prayer meetings.","Leadership training.","Evangelism.","Mentoring.","Family-strengthening programmes.","Community service."]],
["🧑","Youth Department","Discipleship • Leadership • Outreach","To disciple young people and prepare them to become responsible followers and servants of Christ.","",["Youth Bible study.","Prayer.","Evangelism.","Mentoring.","Leadership training.","Music and creative activities.","Conferences and outreach.","Appropriate career and skills guidance."]],
["📡","Media & Technical Department","Media • Technology • Digital Ministry","To use technology and media to communicate the Gospel effectively.","Audio/Sound, Video, Photography, Livestreaming, Graphics Design, Social Media, Website and Projection/Display.",["Managing sound.","Recording services and programmes.","Livestreaming.","Producing approved media content.","Maintaining the Mission website and digital platforms.","Preserving important audiovisual records."]],
["🤝","Ushering Department","Welcome • Order • Hospitality","To provide orderly, welcoming and helpful assistance to worshippers and visitors.","Main Entrance, Auditorium, Protocol Support, Seating Coordination and Visitor Reception.",["Welcoming worshippers.","Providing seating assistance.","Maintaining order.","Assisting visitors.","Coordinating movement during special programmes."]],
["💰","Finance Department","Stewardship • Records • Accountability","To maintain accurate, transparent and accountable financial administration.","Tithes, Offerings, Receipts, Records, Budgeting and Financial Reporting.",["Maintaining financial records.","Recording approved income and expenditure.","Issuing and preserving receipts.","Preparing financial reports.","Assisting with budgeting.","Following Mission financial procedures."]],
["🏠","Welfare Department","Care • Support • Compassion","To coordinate practical care and support for members and approved beneficiaries of the Mission.","Visitation, Benevolence, Hospital/Health Visits, Bereavement Support, Emergency Assistance and Hospitality.",["Visiting members requiring support.","Coordinating approved welfare assistance.","Assisting during bereavements and emergencies.","Coordinating hospitality during major programmes.","Maintaining appropriate welfare records."]]
],books:[["A Bridge to Christ","assets/bridge-to-christ.jpg","assets/bridge-to-christ.jpg"],["A Journey of Hope","assets/journey-of-hope.jpg","assets/journey-of-hope.jpg"]],docs:[["VOTREM Constitution / Mission Ordinance","assets/constitution.pdf"],["VOTREM Forms","assets/votrem-form.pdf"]],media:[],donations:[["Access Bank","0063209953","Ifeanyi Joshua Okonkwo"],["Moniepoint","7062073984","Joshua Okonkwo / Voice on the Rock"]],socials:[["Facebook","https://www.facebook.com/share/1LoPxSnCFs/","Official Facebook"],["YouTube","https://www.youtube.com/@voiceontherock","@voiceontherock"],["X","https://x.com/voiceontherock","@voiceontherock"],["TikTok","https://www.tiktok.com/@voice.on.the.rock","@voice.on.the.rock"],["Instagram","https://www.instagram.com/voiceontherockevangelical","@voiceontherockevangelical"],["WhatsApp","https://wa.me/2347062073984","07062073984"],["Telegram","https://t.me/voiceontherock/12","@voiceontherock/12"]]};

const e=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function render(d){departmentsGrid.innerHTML=d.departments.map((x,i)=>`<article class="department-card"><button class="department-toggle" aria-expanded="false"><span class="department-icon">${e(x[0])}</span><span class="department-title"><strong>${e(x[1])}</strong><small>${e(x[2])}</small></span><span class="department-arrow">+</span></button><div class="department-content"><div class="department-inner"><h3>Purpose</h3><p>${e(x[3])}</p>${x[4]?`<h3>Units</h3><p>${e(x[4])}</p>`:""}<h3>Responsibilities</h3><ul>${x[5].map(v=>`<li>${e(v)}</li>`).join("")}</ul></div></div></article>`).join("");
document.querySelectorAll(".department-toggle").forEach(b=>b.onclick=()=>{const c=b.parentElement,open=c.classList.contains("active");document.querySelectorAll(".department-card.active").forEach(o=>{o.classList.remove("active");o.querySelector("button").setAttribute("aria-expanded","false");o.querySelector(".department-arrow").textContent="+"});if(!open){c.classList.add("active");b.setAttribute("aria-expanded","true");c.querySelector(".department-arrow").textContent="−"}});
booksGrid.innerHTML=d.books.map(x=>`<article class="book-card"><img src="${e(x[1])}" alt="${e(x[0])}"><div class="body"><h3>${e(x[0])}</h3><a class="mini" href="${e(x[2])}" target="_blank">Open</a></div></article>`).join("");
docsGrid.innerHTML=d.docs.map(x=>`<article class="doc-card"><h3>📄 ${e(x[0])}</h3><p>Official Mission document.</p><a class="mini" href="${e(x[1])}" target="_blank">Open document</a></article>`).join("");
mediaGrid.innerHTML=d.media.length?d.media.map(x=>`<article class="media-card"><img src="${e(x.image)}" alt="${e(x.title)}"><div class="body"><h3>${e(x.title)}</h3><p>${e(x.description||"")}</p>${x.url?`<a class="mini" href="${e(x.url)}" target="_blank">View</a>`:""}</div></article>`).join(""):`<article class="doc-card"><h3>Media updates coming soon</h3><p>New photographs, videos and ministry updates will appear here when published.</p></article>`;
donationGrid.innerHTML=d.donations.map(x=>`<article class="donation-card"><h3>${e(x[0])}</h3><p><b>Account Number</b></p><div class="account">${e(x[1])}</div><p><b>Account Name</b><br>${e(x[2])}</p></article>`).join("");
socialGrid.innerHTML=d.socials.map(x=>`<a class="social-card" href="${e(x[1])}" target="_blank" rel="noopener">${e(x[0])}<small>${e(x[2])}</small></a>`).join("")}
document.addEventListener("DOMContentLoaded",()=>{year.textContent=new Date().getFullYear();menu.onclick=()=>nav.classList.toggle("open");render(D)});
